# -*- coding: utf-8 -*-
import os
import yaml
from yaml import Loader, Dumper
from dataclasses import fields
from pathlib import Path
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional, Dict, Any, Union, List, Literal, Type, Set, Collection, Tuple, Callable, Mapping


@dataclass
class ParserABC(ABC):
    def to_yaml(
            self,
            export_path: Optional[Union[str, os.PathLike, Path]],
            default_style: Optional[str] = None,
            default_flow_style: Optional[bool] = False,
            canonical: Optional[bool] = None,
            indent: Optional[int] = 2,
            width: Optional[Union[int, float]] = None,
            allow_unicode: Optional[bool] = None,
            line_break: Optional[str] = None,
            encoding: Optional[str] = None,
            explicit_start: Optional[bool] = None,
            explicit_end: Optional[bool] = None,
            version: Optional[tuple[int, int]] = None,
            tags: Optional[Mapping[str, str]] = None,
            sort_keys: bool = False
    ) -> Optional[str]:
        export_dict: Dict[str, Any] = self.to_dict()

        if export_path is not None:
            # Dump config to YAML file, return None
            with open(export_path, 'w', encoding='utf-8') as file:
                yaml.dump(
                    export_dict, file, Dumper,
                    default_style=default_style,
                    default_flow_style=default_flow_style,
                    canonical=canonical,
                    indent=indent,
                    width=width,
                    allow_unicode=allow_unicode,
                    line_break=line_break,
                    encoding=encoding,
                    explicit_start=explicit_start,
                    explicit_end=explicit_end,
                    version=version,
                    tags=tags,
                    sort_keys=sort_keys
                )
            print(f'Config generated by {self.__class__.__module__}'
                  f'.{self.__class__.__name__} is saved to {export_path}.')
        else:
            # Return str
            return yaml.dump(
                export_dict, None, Dumper,
                default_style=default_style,
                default_flow_style=default_flow_style,
                canonical=canonical,
                indent=indent,
                width=width,
                allow_unicode=allow_unicode,
                line_break=line_break,
                encoding=encoding,
                explicit_start=explicit_start,
                explicit_end=explicit_end,
                version=version,
                tags=tags,
                sort_keys=sort_keys
            )

    def from_yaml(self, import_path: Optional[Union[str, os.PathLike, Path]] = None):
        # Load YAML contents
        with open(import_path, 'r', encoding='utf-8') as file:
            import_dict: Dict[str, Any] = yaml.load(file, Loader)

        for field in fields(self):
            field_name = field.name
            setattr(self, field_name, import_dict[field_name])

    def to_dict(self) -> Dict[str, Any]:
        return vars(self)

    @staticmethod
    def dump_example_to_yaml(
            export_path: Optional[Union[str, os.PathLike, Path]],
            default_style: Optional[str] = None,
            default_flow_style: Optional[bool] = False,
            canonical: Optional[bool] = None,
            indent: Optional[int] = 2,
            width: Optional[Union[int, float]] = None,
            allow_unicode: Optional[bool] = None,
            line_break: Optional[str] = None,
            encoding: Optional[str] = None,
            explicit_start: Optional[bool] = None,
            explicit_end: Optional[bool] = None,
            version: Optional[tuple[int, int]] = None,
            tags: Optional[Mapping[str, str]] = None,
            sort_keys: bool = False
    ) -> Optional[str]:
        raise NotImplementedError(f'Method {ParserABC.dump_example_to_yaml!r} not implemented.')
